// ============================================================================
// JUDGE DASHBOARD TYPES & INTERFACES
// ============================================================================

export interface TimelineDataPoint {
  time: string;
  commits: number;
  phase: "setup" | "feature" | "fix";
}

export interface Milestone {
  name: string;
  timestamp: string;
}

export interface CodeEvolutionTimeline {
  timelineData: TimelineDataPoint[];
  phases: ("setup" | "feature" | "fix")[];
  milestones: Milestone[];
}

export interface Compliance {
  workDuringHackathonPct: number;
  commitTimingStatus: "Early" | "Late" | "Normal";
  locationStatusBadge: string;
  geoFenceWarnings: string[];
}

export interface MemberContribution {
  name: string;
  commits: number;
  linesAdded: number;
  percentage: number;
}

export interface ContributionFairness {
  memberContributions: MemberContribution[];
  fairnessScore: number;
  dominanceIndicator: string | null;
}

export interface IntegrityCodeQuality {
  preBuiltLikelihoodScore: number;
  externalHelpProbability: number;
  indicatorExplanations: string[];
  commitQualityScore: number;
  behavior: "Refactoring" | "Dumping";
  testCasesAdded: boolean;
}

export interface AutoGeneratedSummary {
  keyStrengths: string[];
  keyConcerns: string[];
  judgeNotes: string;
}

export interface TeamSummary {
  id: string;
  teamName: string;
  repoLink: string;
  techStack: string[];
  finalScore: number;
}

export interface Team {
  summary: TeamSummary;
  codeEvolution: CodeEvolutionTimeline;
  compliance: Compliance;
  contributionFairness: ContributionFairness;
  integrityCodeQuality: IntegrityCodeQuality;
  autoGeneratedSummary: AutoGeneratedSummary;
  shortlisted: boolean;
}

export type SortOption = "fairness" | "innovation" | "violations";

export interface Toast {
  id: number;
  type: "success" | "warning" | "info" | "error";
  title: string;
  message: string;
}

export interface JudgeState {
  teams: Team[];
  selectedTeamId: string | null;
  sortBy: SortOption;
  filterShortlisted: boolean;
}
