import type { Team, SortOption } from "../types";

// ============================================================================
// MOCK DATA - 3+ Team Objects
// ============================================================================
const mockTeams: Team[] = [
  {
    summary: {
      id: "team-001",
      teamName: "CodeCrafters",
      repoLink: "https://github.com/codecrafters/hackathon-ai",
      techStack: ["React", "TypeScript", "Node.js", "PostgreSQL", "TensorFlow"],
      finalScore: 87,
    },
    codeEvolution: {
      timelineData: [
        { time: "09:00", commits: 3, phase: "setup" },
        { time: "10:00", commits: 5, phase: "setup" },
        { time: "11:00", commits: 8, phase: "feature" },
        { time: "12:00", commits: 4, phase: "feature" },
        { time: "13:00", commits: 12, phase: "feature" },
        { time: "14:00", commits: 15, phase: "feature" },
        { time: "15:00", commits: 9, phase: "feature" },
        { time: "16:00", commits: 7, phase: "fix" },
        { time: "17:00", commits: 11, phase: "fix" },
        { time: "18:00", commits: 6, phase: "fix" },
      ],
      phases: ["setup", "feature", "fix"],
      milestones: [
        { name: "Project Setup", timestamp: "09:30" },
        { name: "Core Features Complete", timestamp: "14:45" },
        { name: "Final Polish", timestamp: "17:30" },
      ],
    },
    compliance: {
      workDuringHackathonPct: 94,
      commitTimingStatus: "Normal",
      locationStatusBadge: "On-site",
      geoFenceWarnings: [],
    },
    contributionFairness: {
      memberContributions: [
        { name: "Alice", commits: 32, linesAdded: 1540, percentage: 35 },
        { name: "Bob", commits: 28, linesAdded: 1200, percentage: 30 },
        { name: "Charlie", commits: 18, linesAdded: 890, percentage: 20 },
        { name: "Diana", commits: 14, linesAdded: 670, percentage: 15 },
      ],
      fairnessScore: 82,
      dominanceIndicator: null,
    },
    integrityCodeQuality: {
      preBuiltLikelihoodScore: 12,
      externalHelpProbability: 8,
      indicatorExplanations: [
        "Consistent coding style throughout",
        "Gradual complexity increase observed",
        "No suspicious large commits",
      ],
      commitQualityScore: 88,
      behavior: "Refactoring",
      testCasesAdded: true,
    },
    autoGeneratedSummary: {
      keyStrengths: [
        "Excellent team collaboration",
        "Clean code architecture",
        "Innovative AI integration",
        "Comprehensive documentation",
      ],
      keyConcerns: [
        "Minor test coverage gaps",
        "Could improve error handling",
      ],
      judgeNotes: "",
    },
    shortlisted: false,
  },
  {
    summary: {
      id: "team-002",
      teamName: "ByteBlasters",
      repoLink: "https://github.com/byteblasters/eco-tracker",
      techStack: ["Vue.js", "Python", "FastAPI", "MongoDB", "Docker"],
      finalScore: 79,
    },
    codeEvolution: {
      timelineData: [
        { time: "09:00", commits: 2, phase: "setup" },
        { time: "10:00", commits: 3, phase: "setup" },
        { time: "11:00", commits: 15, phase: "feature" },
        { time: "12:00", commits: 2, phase: "feature" },
        { time: "13:00", commits: 18, phase: "feature" },
        { time: "14:00", commits: 8, phase: "feature" },
        { time: "15:00", commits: 5, phase: "fix" },
        { time: "16:00", commits: 20, phase: "fix" },
        { time: "17:00", commits: 4, phase: "fix" },
        { time: "18:00", commits: 3, phase: "fix" },
      ],
      phases: ["setup", "feature", "fix"],
      milestones: [
        { name: "Environment Ready", timestamp: "09:45" },
        { name: "MVP Complete", timestamp: "15:00" },
        { name: "Bug Fixes Done", timestamp: "17:45" },
      ],
    },
    compliance: {
      workDuringHackathonPct: 78,
      commitTimingStatus: "Late",
      locationStatusBadge: "Mixed",
      geoFenceWarnings: [
        "2 commits from outside venue at 16:30",
        "Location change detected at 14:00",
      ],
    },
    contributionFairness: {
      memberContributions: [
        { name: "Eve", commits: 45, linesAdded: 2100, percentage: 55 },
        { name: "Frank", commits: 20, linesAdded: 800, percentage: 25 },
        { name: "Grace", commits: 15, linesAdded: 600, percentage: 20 },
      ],
      fairnessScore: 58,
      dominanceIndicator: "Eve (55%) - High dominance warning",
    },
    integrityCodeQuality: {
      preBuiltLikelihoodScore: 35,
      externalHelpProbability: 22,
      indicatorExplanations: [
        "Large initial commit detected",
        "Some boilerplate code patterns",
        "Commit messages inconsistent",
      ],
      commitQualityScore: 65,
      behavior: "Dumping",
      testCasesAdded: false,
    },
    autoGeneratedSummary: {
      keyStrengths: [
        "Innovative concept",
        "Good UI/UX design",
        "Environmental impact focus",
      ],
      keyConcerns: [
        "Uneven contribution distribution",
        "Possible pre-built components",
        "Late commit pattern",
        "Missing tests",
      ],
      judgeNotes: "",
    },
    shortlisted: false,
  },
  {
    summary: {
      id: "team-003",
      teamName: "NeuralNinjas",
      repoLink: "https://github.com/neuralninjas/health-ai",
      techStack: ["Next.js", "Go", "Redis", "Kubernetes", "PyTorch"],
      finalScore: 92,
    },
    codeEvolution: {
      timelineData: [
        { time: "09:00", commits: 4, phase: "setup" },
        { time: "10:00", commits: 6, phase: "setup" },
        { time: "11:00", commits: 7, phase: "feature" },
        { time: "12:00", commits: 9, phase: "feature" },
        { time: "13:00", commits: 10, phase: "feature" },
        { time: "14:00", commits: 11, phase: "feature" },
        { time: "15:00", commits: 8, phase: "feature" },
        { time: "16:00", commits: 6, phase: "fix" },
        { time: "17:00", commits: 5, phase: "fix" },
        { time: "18:00", commits: 4, phase: "fix" },
      ],
      phases: ["setup", "feature", "fix"],
      milestones: [
        { name: "Architecture Design", timestamp: "09:15" },
        { name: "AI Model Integrated", timestamp: "13:30" },
        { name: "Production Ready", timestamp: "18:00" },
      ],
    },
    compliance: {
      workDuringHackathonPct: 98,
      commitTimingStatus: "Early",
      locationStatusBadge: "On-site",
      geoFenceWarnings: [],
    },
    contributionFairness: {
      memberContributions: [
        { name: "Henry", commits: 22, linesAdded: 980, percentage: 26 },
        { name: "Ivy", commits: 21, linesAdded: 950, percentage: 25 },
        { name: "Jack", commits: 20, linesAdded: 920, percentage: 24 },
        { name: "Kim", commits: 19, linesAdded: 880, percentage: 25 },
      ],
      fairnessScore: 96,
      dominanceIndicator: null,
    },
    integrityCodeQuality: {
      preBuiltLikelihoodScore: 5,
      externalHelpProbability: 3,
      indicatorExplanations: [
        "Organic code growth pattern",
        "Consistent commit sizes",
        "Well-documented changes",
        "Pair programming evidence",
      ],
      commitQualityScore: 94,
      behavior: "Refactoring",
      testCasesAdded: true,
    },
    autoGeneratedSummary: {
      keyStrengths: [
        "Exceptional team balance",
        "High code quality",
        "Advanced tech stack mastery",
        "Complete test coverage",
        "Excellent documentation",
      ],
      keyConcerns: [],
      judgeNotes: "",
    },
    shortlisted: true,
  },
  {
    summary: {
      id: "team-004",
      teamName: "PixelPioneers",
      repoLink: "https://github.com/pixelpioneers/ar-shopping",
      techStack: ["React Native", "Firebase", "ARKit", "Node.js"],
      finalScore: 74,
    },
    codeEvolution: {
      timelineData: [
        { time: "09:00", commits: 1, phase: "setup" },
        { time: "10:00", commits: 2, phase: "setup" },
        { time: "11:00", commits: 3, phase: "setup" },
        { time: "12:00", commits: 5, phase: "feature" },
        { time: "13:00", commits: 8, phase: "feature" },
        { time: "14:00", commits: 12, phase: "feature" },
        { time: "15:00", commits: 18, phase: "feature" },
        { time: "16:00", commits: 22, phase: "fix" },
        { time: "17:00", commits: 15, phase: "fix" },
        { time: "18:00", commits: 8, phase: "fix" },
      ],
      phases: ["setup", "feature", "fix"],
      milestones: [
        { name: "Setup Complete", timestamp: "11:00" },
        { name: "AR Features Done", timestamp: "15:30" },
        { name: "App Deployed", timestamp: "18:00" },
      ],
    },
    compliance: {
      workDuringHackathonPct: 85,
      commitTimingStatus: "Late",
      locationStatusBadge: "On-site",
      geoFenceWarnings: ["Slow start detected"],
    },
    contributionFairness: {
      memberContributions: [
        { name: "Leo", commits: 38, linesAdded: 1800, percentage: 45 },
        { name: "Mia", commits: 25, linesAdded: 1100, percentage: 30 },
        { name: "Noah", commits: 18, linesAdded: 750, percentage: 25 },
      ],
      fairnessScore: 68,
      dominanceIndicator: "Leo (45%) - Moderate dominance",
    },
    integrityCodeQuality: {
      preBuiltLikelihoodScore: 25,
      externalHelpProbability: 18,
      indicatorExplanations: [
        "Some template usage detected",
        "AR framework heavily utilized",
        "Good custom implementation",
      ],
      commitQualityScore: 72,
      behavior: "Refactoring",
      testCasesAdded: false,
    },
    autoGeneratedSummary: {
      keyStrengths: [
        "Creative AR implementation",
        "Good mobile performance",
        "Engaging user experience",
      ],
      keyConcerns: [
        "Late start to development",
        "Some contribution imbalance",
        "No automated tests",
      ],
      judgeNotes: "",
    },
    shortlisted: false,
  },
];

// Simulated API delay
const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Judge Dashboard Service
 */
export const judgeService = {
  /**
   * Fetch all teams for evaluation
   */
  async getTeams(): Promise<Team[]> {
    await delay(500);
    return [...mockTeams];
  },

  /**
   * Get a single team by ID
   */
  async getTeamById(teamId: string): Promise<Team | null> {
    await delay(200);
    return mockTeams.find((t) => t.summary.id === teamId) || null;
  },

  /**
   * Update judge notes for a team
   */
  async updateJudgeNotes(teamId: string, notes: string): Promise<boolean> {
    await delay(300);
    // In production, this would save to database
    return true;
  },

  /**
   * Toggle team shortlist status
   */
  async toggleShortlist(teamId: string): Promise<boolean> {
    await delay(200);
    return true;
  },

  /**
   * Submit final evaluation
   */
  async submitEvaluation(
    teamId: string,
    data: { notes: string; score: number }
  ): Promise<boolean> {
    await delay(400);
    return true;
  },

  /**
   * Sort teams by criteria
   */
  sortTeams(teams: Team[], sortBy: SortOption): Team[] {
    const sorted = [...teams];
    
    switch (sortBy) {
      case "fairness":
        return sorted.sort(
          (a, b) => b.contributionFairness.fairnessScore - a.contributionFairness.fairnessScore
        );
      case "innovation":
        return sorted.sort((a, b) => b.summary.finalScore - a.summary.finalScore);
      case "violations":
        return sorted.sort(
          (a, b) =>
            a.compliance.geoFenceWarnings.length - b.compliance.geoFenceWarnings.length
        );
      default:
        return sorted;
    }
  },
};

export default judgeService;
